apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-orders
  namespace: ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-orders
  template:
    metadata:
      labels:
        app: mongo-orders
    spec:
      containers:
        - name: mongo
          image: mongo:7
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-orders
  namespace: ms
spec:
  selector:
    app: mongo-orders
  ports:
    - port: 27017
      targetPort: 27017